### ISSUE TITLE
Lab 2 (задания 1-9)

### ISSUE THREAD

**Issue by lasbio** [Boliti/LR.DataBase#2]
1. Task 2.3 и далее - условия отбора полей неправильные, не соответствуют заданию.
2. Task 2.7 - не эффективно. А что делать когда будет пару десятков id. Добавлять двадцать условий OR? м.б. лучше использовать IN (...)?  
3. Task 2.8 - по заданию должна быть 1 выборка и возвращаемые поля должны содержать "качественную стоимость".
4. Task 2.,9 - неэффективно, LIKE свмая междленная операция

**Comment by irinamatveeva** [comment]
Задание 6 - лучше выводить не все данные, а только "объекты" (если просят только "объекты"). Это касается и следующих заданий тоже.
Задание 7 - рекомендуется OR использовать IN(....)
Задание 8 - не выполнено, нет столбца качественной стоимости со значениями "дорогой" и "дешевый".
Задание 9 - не рекомендуется использовать LIKE, не нужно выводить все данные пользователей, достаточно фамилий и имен, например, и memid (это касается и следующих заданий).
Задания 11 и далее - пока не сделаны

**Comment by lasbio** [comment]
2.7 между IN и ( все же лучше иметь пробел.
2.9 лучше joindate >= '2012-09-01'
2.11 - 'new' => keyword, а все ключевые термины не рекомендовано использовать в качестве названий колонок.
2.14 - неправильные условия отбора.
